### ISSUE TITLE
Since Joomla update Isis template JUI not working.

### ISSUE THREAD

**Issue by rickjs** [asika32764/joomla-bootstrap3-isis-template#12]
Default Isis stopped working on Joomla 3.4 update. Don't see menu at left. Strange thing, a new install of Joomla 3.4, Isis works fine. I tried installing this updated Isis, no change. I have a module called News Show Pro GK5, the menu like the Data Source only expanded using the Isis Template. NSP menus don't work anymore.

**Comment by asika32764** [comment]
This is not default isis, and this template is another template called isis3, you can't update isis by this template.

About NSP menus, could you upload screenshot for me?

**Comment by rickjs** [comment]
Hi Simon,

I thought it was a upgrade, no problem though because I uninstalled the default Isis and installed the new Isis3. Don't need to send you NSP image clip because I found out why. The template manager never switches over to Isis. Using Firebug, found it was using Hathor css, did some Netbeans tracing, it's still using the Hathor template even though Isis3 is default. I'm not that familar backend architecture, can you tell me what to trace and where the selection is stored?

Thanks,

Rick

**Comment by asika32764** [comment]
I think the problem is in Joomla core.

You could go to Joomla cms official repository to ask this question
https://github.com/joomla/joomla-cms

Here is 3rd extension repo, so I can't answer you about Joomla core issues.

**Comment by rickjs** [comment]
Hi,

There seems to be a problem with paths in the legacy controller, legacy.php. At a certain point it's dropping a characters from the path. It's strange, the $paths  variable is ok before the $this->getView call, then $paths loses characters from the string going into the function getView. Guess this is one Joomla support.

Rick
