### ISSUE TITLE
Color  field display fix

### ISSUE THREAD

**Issue by manchumahara** [asika32764/joomla-bootstrap3-isis-template#7]
I found color field was not showing properly.

In template.less file I used this code and then complied again.

.minicolors-theme-bootstrap .minicolors-input{
  width: auto !important;
  height: auto !important;
}

before: http://www.webpagescreenshot.info/img/53a7b8f6802778-88456146
after: http://www.webpagescreenshot.info/img/53a7b9088fb568-98091536

BTW, which less parser are you using ?

**Comment by asika32764** [comment]
Fixed in lastest version
