### ISSUE TITLE
Article editing tabs disappeared

### ISSUE THREAD

**Issue by mlakic** [asika32764/joomla-bootstrap3-isis-template#9]
I'm having a problem with my Joomla 3.3.6 BS3 T3 website isis3 administrator template. In the backend, when I disable "Debug System" in Global Configuration --> System, the "Publishing", "Images and links", "Options", "Configure Edit Screen" and "Permissions" tabs disappear from the article editing page (see image attached). When I open the console in Chrome, it displays some errors on this page (also attached).

When I switch to the hathor template the options reappear when I edit an article. I have downloaded the latest version of the isis3 template and the issue is still there.

![snap1](https://cloud.githubusercontent.com/assets/6440268/5328792/e1e36dbc-7d8e-11e4-8556-9784866bf1fa.jpg)
![snap2](https://cloud.githubusercontent.com/assets/6440268/5328793/e1e63268-7d8e-11e4-801b-aeab13e0fa20.jpg)

Could someone please help me with this?

**Comment by asika32764** [comment]
There's no any update of this issue. closed.
